### ISSUE TITLE
Spam: Checking against rarchives still fails.  

### ISSUE THREAD

**Issue by tek0011** [tek0011/RedditInfoBot#13]
filtering still fails against rarchives.  Text filters fail.  Some links fail.  Tumblr always fails.

**Comment by tek0011** [comment]
Also seems that text that is in spambot filters doesnt get removed if it is part of a link title that the bot creates

**Comment by tek0011** [comment]
Better now, but still failing.

Missed this filter - http://spambot.rarchives.com/#filter=link&text=www.sex.com/

**Comment by jacobstein123** [comment]
Should be fixed now with the latest rarchives update fix, but I'm leaving this open until more testing is done to ensure it's actually fixed.

**Comment by tek0011** [comment]
likely solved
