### ISSUE TITLE
ascii codec can not decode characters in position

### ISSUE THREAD

**Issue by tek0011** [tek0011/RedditInfoBot#14]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 299, in <module>
    parse_comments(all_comments)
  File "info_bot_nsfw.py", line 185, in parse_comments
    if any(i in str(comment['link_url']) for i in ['.tif', '.tiff', '.gif', '.jpeg', 'jpg', '.jif', '.jfif', '.jp2', '.jpx', '.j2k', '.j2c', '.fpx', '.pcd', '.png']):
  File "info_bot_nsfw.py", line 185, in <genexpr>
    if any(i in str(comment['link_url']) for i in ['.tif', '.tiff', '.gif', '.jpeg', 'jpg', '.jif', '.jfif', '.jp2', '.jpx', '.j2k', '.j2c', '.fpx', '.pcd', '.png']):
UnicodeEncodeError: 'ascii' codec can't encode characters in position 56-61: ordinal not in range(128)

**Comment by jacobstein123** [comment]
It will now ensure that the url is valid ascii before proceeding.
