### ISSUE TITLE
/u/info_bot_nsfw not being found

### ISSUE THREAD

**Issue by tek0011** [tek0011/RedditInfoBot#18]
This will be where I put the links for user calls the bot is not responding to.  You'll notice there are replies, that is because I reposted them and ran the bot against them.  Which leads me to believe it is a timing issue of some sort.  Perhaps can't handle so many calls?

These are probably all NSFW, unless marked otherwise.  The other bot I set to ignore anything but picture extensions and its fine.  The nsfw bot has issues though.

http://www.reddit.com/r/Bondage/comments/3484jw/standing_orgasm/
http://www.reddit.com/r/NSFW_GIF/comments/34adsc/wind_steals_top/

**Comment by jacobstein123** [comment]
This should be resolved with the new find_username_mentions() function
