### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by tek0011** [tek0011/RedditInfoBot#24]
detected keyword:  Traceback (most recent call last):
  File "info_bot_nsfw.py", line 361, in <module>
    find_keywords(all_comments)
  File "info_bot_nsfw.py", line 254, in find_keywords
    print comment.body
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u0ca0' in position 26: character maps to <undefined>

**Comment by tek0011** [comment]
. .retrieving: http://www.reddit.com/r/shorthairchicks/comments/35e1ey/aaaa/cr3ixj9.json
params: None
data: None

detected keyword:  Traceback (most recent call last):
  File "info_bot_nsfw.py", line 361, in <module>
    find_keywords(all_comments)
  File "info_bot_nsfw.py", line 254, in find_keywords
    print comment.body
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\xd7' in position 68: character maps to <undefined>

**Comment by jacobstein123** [comment]
This is just an issue with the printing encoding non-ascii characters, so I just try-catch'd it
