### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'list' objects

### ISSUE THREAD

**Issue by tek0011** [tek0011/RedditInfoBot#26]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 412, in <module>
    find_username_mentions()
  File "info_bot_nsfw.py", line 267, in find_username_mentions
    give_more_info(comment)
  File "info_bot_nsfw.py", line 180, in give_more_info
    karmadecay_formatted = format_results(get_karmadecay_results(comment.submission))
  File "info_bot_nsfw.py", line 143, in format_results
    ascii_final = get_nonspam_links(ascii_filtered) #filter the links for spam
  File "info_bot_nsfw.py", line 127, in get_nonspam_links
    print "passed domains: "+ passed_domains
TypeError: cannot concatenate 'str' and 'list' objects

**Comment by jacobstein123** [comment]
On my phone now but if you turn it into str(passed_domains) it should fix this.

**Comment by tek0011** [comment]
k.  did that.  It seemed to be a random crash, so Ill have to wait to see
if it happens again.  yay! Super fast reply.  thanks.

On Wed, May 13, 2015 at 12:08 PM, jacobstein123 <notifications@github.com>
wrote:

> On my phone now but if you turn it into str(passed_domains) it should fix
> this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tek0011/RedditInfoBot/issues/26#issuecomment-101748688>
> .
>



-- 
Jeff
