### ISSUE TITLE
JSON Object Crash

### ISSUE THREAD

**Issue by tek0011** [tek0011/RedditInfoBot#6]
http://i.imgur.com/NazAYt9.png

I think I fixed it with:

def get_all_comments(stream):

    a = session_client.get(stream, headers=headers)

    try:

        js = json.loads(a.content)

    except ValueError:

        #decoding failed

        pass

    b =  js['data']['children']

    comments_json = [i['data'] for i in b]

    return comments_json`

Please confirm

**Comment by jacobstein123** [comment]
Changed get_all_comments to this:

    def get_all_comments(stream):
        a = session_client.get(stream, headers=headers)
        try:
            js = json.loads(a.content)
            b =  js['data']['children']
            comments_json = [i['data'] for i in b]
            return comments_json
        except ValueError:
            return None

and made it so if it returns none, it will skip that comment stream
